import {
  createContext, createElement, useCallback, useContext, useEffect,
  useMemo, useState, type ReactNode,
} from "react";

export type Language = "en" | "de";
const STORAGE_KEY = "widash.language";
const DEFAULT_LANGUAGE: Language = "en";

const dict = {
  en: {
    "header.locationFilter": "Location filter",
    "header.locationCount": "{count} active cases in {loc}",
    "header.locationShow": "Show {loc}",
    "header.locationHide": "Hide {loc}",
    "header.themeLight": "Switch to light theme",
    "header.themeDark": "Switch to dark theme",
    "header.refresh": "Reload data",
    "header.settings": "Region & report settings",
    "settings.title": "Regions & reports",
    "settings.subtitle": "Tell WiDash which GUS report drives the dashboard. Sites and team aliases come along automatically.",
    "settings.subtitleMulti": "Add one or more GUS reports. WiDash merges their data so you can watch multiple regions at once.",
    "settings.detected": "Detected for you",
    "settings.detectedHasReport": "Looks like you work in {prefix}. We have a report on file:",
    "settings.detectedAlreadyAdded": "We already added the report for your detected region.",
    "settings.detectedNoReport": "Looks like you work in {prefix}, but no report is registered yet for that region. Paste your report id below.",
    "settings.detectedUnknown": "Couldn't detect a region from your recent cases. Paste your report id below.",
    "settings.knownRegions": "Regions on file",
    "settings.activeReports": "Active reports",
    "settings.noReports": "No reports configured yet — add at least one below.",
    "settings.add": "Add",
    "settings.remove": "Remove",
    "settings.addRegionLabel": "Add a region",
    "settings.addCustomLink": "Add a custom report id…",
    "settings.hideCustom": "Hide custom input",
    "settings.reportIdLabel": "Report ID",
    "settings.reportIdHint": "Open your active RMA report in GUS, copy the 18-character id from the URL (starts with 00O).",
    "settings.invalidId": "That doesn't look like a Salesforce id. Should be 15 or 18 alphanumeric characters.",
    "settings.duplicateId": "This report id is already in the list.",
    "settings.multiWarning": "Loading multiple reports adds ~2-3s per report on the initial fetch — Salesforce serializes the requests.",
    "settings.save": "Save",
    "header.languageMenu": "Language",
    "header.fontSize": "Font size: {size} (click to cycle)",
    "writeMode.on": "Writes ON",
    "writeMode.off": "Writes OFF",
    "writeMode.titleOn": "Write mode is ON — actions will mutate Salesforce on confirmation. Click to disable.",
    "writeMode.titleOff": "Write mode is OFF — actions only show what they would do. Click to enable.",
    "coolan.connected": "Coolan connected",
    "coolan.disconnected": "Coolan disconnected",
    "coolan.connect": "Connect Coolan",
    "coolan.modalTitle": "Connect to Coolan",
    "coolan.intro": "Coolan uses its own SSO and won't accept your sf-CLI token. Paste the Authorization header your browser uses for Coolan once and we'll keep it on disk.",
    "coolan.stepOpen": "Open Coolan in your browser and log in normally.",
    "coolan.stepDevtools": "Open DevTools → Network, click any request to /v1/graphql, copy the full 'Authorization' request header.",
    "coolan.stepPaste": "Paste it below. The cookie is usually optional — leave empty unless required.",
    "coolan.tokenLabel": "Authorization header",
    "coolan.cookieLabel": "Cookie header (optional)",
    "coolan.save": "Save & test",
    "coolan.clear": "Clear",
    "coolan.autoTitle": "Auto-connect",
    "coolan.autoIntro": "Let WiDash drive a headless browser through Coolan's SSO. The first run needs MFA, so click 'Open browser window' if asked.",
    "coolan.autoNeedsInteraction": "MFA or Salesforce login is required. Click below to open a Chromium window where you can complete it once. Future refreshes stay headless.",
    "coolan.autoTryHeadless": "Auto-connect (headless)",
    "coolan.autoOpenBrowser": "Open browser window",
    "coolan.manualToggle": "Or paste a token manually",

    "common.loading": "Loading…",
    "common.loadingData": "Loading data…",
    "common.unknownError": "Unknown error",
    "common.authExpired": "Session expired. Run `sf org login` in the terminal and click refresh.",
    "auth.bannerTitle": "Salesforce session expired",
    "auth.bannerBody": "Run this in your terminal, then click Retry. The dashboard will reconnect with your fresh token automatically.",
    "auth.copy": "Copy",
    "auth.copied": "Copied!",
    "auth.retry": "Retry",

    "sheet.minimize": "Minimize",
    "sheet.restore": "Open",
    "sheet.close": "Close",
    "sheet.pinTabs": "Pin tab bar — keep all tabs above the open sheet",
    "sheet.unpinTabs": "Unpin tab bar",
    "sheet.dragHandle": "Drag to resize",
    "sheet.heading": "Case · {name}",
    "sheet.placeholderActions": "Action buttons (status, comment, owner) will land here once we wire them up — read-only details for now.",
    "sheet.loadingLive": "Loading live case data…",
    "sheet.fallbackMock": "Showing cached snapshot — couldn't reach the backend for live data.",
    "sheet.liveBadge": "● LIVE",
    "sheet.liveTitle": "Showing live data from Salesforce",
    "sheet.cachedBadge": "● CACHED",
    "sheet.fieldStatus": "Status",
    "sheet.fieldPriority": "Priority",
    "sheet.fieldLocation": "Location",
    "sheet.fieldSubject": "Subject",
    "sheet.fieldAssetName": "Asset",
    "sheet.fieldAssetLocation": "Asset path",
    "sheet.fieldAssetType": "Asset type",
    "sheet.fieldCreated": "Created",
    "sheet.fieldAssignee": "Assignee",
    "sheet.fieldDescription": "Description",
    "sheet.fieldCoolan": "Coolan reporting state",

    "chatter.tabChatter": "Chatter",
    "chatter.tabCaseComments": "Case Comments",
    "chatter.tabEmail": "Emails",
    "chatter.placeholder": "Write a comment…",
    "chatter.replyPlaceholder": "Reply…",
    "chatter.post": "Post",
    "chatter.reply": "Reply",
    "chatter.cancelReply": "Cancel",
    "chatter.empty": "Nothing here yet.",
    "chatter.edit": "Edit",
    "chatter.save": "Save",
    "chatter.replies": "Replies",

    "sheet.editStatus": "Change status",
    "sheet.vendorCaseNumber": "Vendor Case Number",
    "sheet.vendorCaseNumberHint": "An external vendor is dispatched on this case — escort required.",
    "sheet.pickParentFirst": "Pick the parent category first",
    "sheet.editSection": "Edit",
    "sheet.saveSection": "Review changes",
    "sheet.cancelSection": "Cancel",
    "sheet.collapseSection": "Collapse {name}",
    "sheet.expandSection": "Expand {name}",

    "edit.confirmTitle": "Review changes",
    "edit.confirmSubtitle": "{count} field(s) on case {caseNumber}",
    "edit.sectionCase": "Case",
    "edit.sectionAsset": "Asset",
    "edit.colField": "Field",
    "edit.colOld": "Current value",
    "edit.colNew": "New value",
    "edit.cancel": "Cancel",
    "edit.edit": "Back to edit",
    "edit.confirmWrite": "Confirm and write",
    "edit.confirmDryRun": "Confirm (dry-run)",
    "edit.dryRunHeader": "Write mode is OFF.",
    "edit.dryRunBody": "Confirming will only log the intended change. Turn the Writes pill in the header on to actually push to Salesforce.",
    "edit.toastSaved": "Saved",
    "edit.toastDryRun": "Dry-run logged",
    "edit.toastPosted": "Comment posted",
    "common.close": "Close",
    "common.openInGus": "Open in GUS",
    "common.openInGusAndMark": "Open in GUS (also marks as seen)",
    "common.clickForFullText": "Click for full text",
    "common.tooltipClose": "Close tooltip",
    "common.tooltipResize": "Drag to resize",

    "donut.active": "ACTIVE",
    "donut.rtsTodayShort": "RTS today",
    "donut.rtsTodayFull": "Return to Service today",
    "donut.totalRuntime": "Total runtime",
    "donut.hint": "Click a segment in the pie chart to open the ticket list for that status.",

    "legend.title": "Active RMA overview",
    "legend.rtsToday": "Return to Service",
    "legend.rtsTodayHint": "today",
    "legend.rtsTodayTitle": "Number of Frankfurt cases that switched to Return to Service today",
    "legend.myOpen": "Still open by me",
    "legend.myOpenTitle": "Cases you set to Return to Service that are still not closed. Click to expand/collapse.",
    "legend.closed": "Already closed",
    "legend.closedHint": "(180d)",
    "legend.closedTitle": "Tickets you set to Return to Service that have since been closed (last 180 days)",
    "legend.tableTicket": "Ticket",
    "legend.tableLocation": "Loc.",
    "legend.tableSubject": "Subject",
    "legend.tableSetAt": "Set at",

    "details.heading": "Details: {status} ({count})",
    "details.colPriority": "Prio",
    "details.colTicketId": "Ticket ID",
    "details.colLocation": "Location",
    "details.colType": "Subject",
    "details.colCreated": "Created",
    "details.colStatusChanged": "Status since",
    "details.colAssignee": "Assignee",
    "details.colAssetName": "Asset",
    "details.colAssetLocation": "Asset path",
    "details.colAssetType": "Asset type",
    "details.colDescription": "Description",
    "details.colCoolan": "Coolan",
    "details.colGus": "GUS",
    "details.tooltipTitle": "Subject · {name}",
    "details.coolanTooltipTitle": "Coolan · {name}",
    "details.coolanNoneAvailable": "No Coolan links",
    "details.componentTooltipFor": "Component on case {ticketId}",
    "details.componentNoAttributes": "Coolan didn't return any details for this component.",
    "details.coolanStateMissing": "Reporting state: Missing — host is not reporting in Coolan.",
    "details.coolanStateActive": "Reporting state: Active — host is alive and reporting.",
    "details.coolanStateUnknown": "Reporting state: unknown — Coolan has no record for this asset.",
    "details.columnsManager": "Columns",
    "details.columnsManagerTitle": "Columns",
    "details.columnsManagerReset": "Reset",
    "details.columnsManagerHint": "Drag the handle to reorder. Uncheck to hide.",
    "filter.label": "Filter",
    "filter.column": "Filter column",
    "filter.columnPlaceholder": "Pick column…",
    "filter.value": "Filter value",
    "filter.placeholder": "Type to filter…",
    "filter.clear": "Clear filter",
    "filter.counter": "Showing {shown} of {total}",

    "activity.title": "Activity log",
    "activity.outsideHint": "outside {start}–{end} highlighted",
    "activity.outsideHours": "Outside working hours ({start}–{end})",
    "activity.newCase": "New case",
    "activity.mentionsMe": "Mentions you / @DCEng-FRA3",
    "activity.botsOn": "Bots on",
    "activity.botsOff": "Bots off",
    "activity.toggleBotsTitle": "Toggle service-account events (e.g. svc_grok-fra)",
    "activity.filterAll": "All",
    "activity.filterStatus": "Status",
    "activity.filterComment": "Comments",
    "activity.filterMe": "Me",
    "activity.filterMeTitle": "Only events involving {name} (actor or mention)",
    "activity.statusFilter": "Status filter",
    "activity.statusClear": "Clear",
    "activity.searchComments": "Search comments…",
    "activity.searchTickets": "Ticket #",
    "activity.searchTicketsTitle": "Type a ticket number to see only that case's full timeline. Other filters are ignored while this is active.",
    "activity.colTime": "Time",
    "activity.colTicket": "Ticket",
    "activity.colLocation": "Loc.",
    "activity.colEvent": "Event",
    "activity.colActor": "Actor",
    "activity.colGus": "GUS",
    "activity.markSeen": "Mark as seen",
    "activity.markNew": "Mark as new",
    "activity.markSeenTitle": "New — mark as seen",
    "activity.markNewTitle": "Seen — mark as new",
    "activity.eventStatus": "Status:",
    "activity.eventComment": "Comment:",
    "activity.empty": "No activity",
    "activity.commentTooltipTitle": "Comment · {ticketId}",
  },
  de: {
    "header.locationFilter": "Standort-Filter",
    "header.locationCount": "{count} aktive Fälle in {loc}",
    "header.locationShow": "{loc} einblenden",
    "header.locationHide": "{loc} ausblenden",
    "header.themeLight": "Helles Theme aktivieren",
    "header.themeDark": "Dunkles Theme aktivieren",
    "header.refresh": "Daten neu laden",
    "header.settings": "Region & Report-Einstellungen",
    "settings.title": "Regionen & Reports",
    "settings.subtitle": "Sage WiDash welcher GUS-Report das Dashboard speist. Standorte und Team-Aliase werden automatisch übernommen.",
    "settings.subtitleMulti": "Füge einen oder mehrere GUS-Reports hinzu. WiDash mischt die Daten, sodass du mehrere Regionen gleichzeitig sehen kannst.",
    "settings.detected": "Für dich erkannt",
    "settings.detectedHasReport": "Sieht so aus als arbeitest du in {prefix}. Wir haben einen Report hinterlegt:",
    "settings.detectedAlreadyAdded": "Der Report für deine erkannte Region ist bereits hinzugefügt.",
    "settings.detectedNoReport": "Sieht so aus als arbeitest du in {prefix}, aber für diese Region ist noch kein Report hinterlegt. Trage unten deine Report-ID ein.",
    "settings.detectedUnknown": "Konnte aus deinen letzten Cases keine Region ableiten. Trage unten deine Report-ID ein.",
    "settings.knownRegions": "Hinterlegte Regionen",
    "settings.activeReports": "Aktive Reports",
    "settings.noReports": "Noch keine Reports konfiguriert — füge unten mindestens einen hinzu.",
    "settings.add": "Hinzufügen",
    "settings.remove": "Entfernen",
    "settings.addRegionLabel": "Region hinzufügen",
    "settings.addCustomLink": "Eigene Report-ID hinzufügen…",
    "settings.hideCustom": "Eigenes Eingabefeld ausblenden",
    "settings.reportIdLabel": "Report-ID",
    "settings.reportIdHint": "Öffne deinen aktiven RMA-Report in GUS, kopiere die 18-stellige ID aus der URL (beginnt mit 00O).",
    "settings.invalidId": "Das sieht nicht nach einer Salesforce-ID aus. Sollten 15 oder 18 alphanumerische Zeichen sein.",
    "settings.duplicateId": "Diese Report-ID ist schon in der Liste.",
    "settings.multiWarning": "Mehrere Reports zu laden kostet ~2-3s zusätzlich pro Report — Salesforce serialisiert die Anfragen.",
    "settings.save": "Speichern",
    "header.languageMenu": "Sprache",
    "header.fontSize": "Schriftgröße: {size} (Klick zum Wechseln)",
    "writeMode.on": "Schreiben AN",
    "writeMode.off": "Schreiben AUS",
    "writeMode.titleOn": "Schreibmodus ist AN — Aktionen schreiben nach Bestätigung wirklich nach Salesforce. Klick zum Deaktivieren.",
    "writeMode.titleOff": "Schreibmodus ist AUS — Aktionen zeigen nur was sie tun würden. Klick zum Aktivieren.",
    "coolan.connected": "Coolan verbunden",
    "coolan.disconnected": "Coolan getrennt",
    "coolan.connect": "Coolan verbinden",
    "coolan.modalTitle": "Coolan verbinden",
    "coolan.intro": "Coolan hat eigenes SSO und akzeptiert dein sf-CLI-Token nicht. Füge den Authorization-Header deines Browsers für Coolan einmalig ein, wir merken ihn uns auf der Festplatte.",
    "coolan.stepOpen": "Öffne Coolan im Browser und logge dich normal ein.",
    "coolan.stepDevtools": "DevTools → Network → einen Request auf /v1/graphql anklicken → kompletten 'Authorization'-Request-Header kopieren.",
    "coolan.stepPaste": "Hier einfügen. Cookie ist meist optional — leer lassen, wenn nicht nötig.",
    "coolan.tokenLabel": "Authorization-Header",
    "coolan.cookieLabel": "Cookie-Header (optional)",
    "coolan.save": "Speichern & testen",
    "coolan.clear": "Löschen",
    "coolan.autoTitle": "Auto-Verbinden",
    "coolan.autoIntro": "WiDash kann einen unsichtbaren Browser durch Coolans SSO leiten. Beim ersten Mal ist MFA nötig — falls dazu aufgefordert, klicke auf 'Browser-Fenster öffnen'.",
    "coolan.autoNeedsInteraction": "MFA oder Salesforce-Login erforderlich. Unten klicken, um ein Chromium-Fenster zu öffnen — du machst MFA einmal, danach läuft es unsichtbar.",
    "coolan.autoTryHeadless": "Auto-Verbinden (unsichtbar)",
    "coolan.autoOpenBrowser": "Browser-Fenster öffnen",
    "coolan.manualToggle": "Oder Token manuell einfügen",

    "common.loading": "Lade…",
    "common.loadingData": "Lade Daten…",
    "common.unknownError": "Unbekannter Fehler",
    "common.authExpired": "Session abgelaufen. Bitte im Terminal `sf org login` ausführen und Refresh klicken.",
    "auth.bannerTitle": "Salesforce-Session abgelaufen",
    "auth.bannerBody": "Diesen Befehl im Terminal ausführen, dann auf 'Erneut versuchen' klicken. Das Dashboard verbindet sich automatisch mit dem frischen Token.",
    "auth.copy": "Kopieren",
    "auth.copied": "Kopiert!",
    "auth.retry": "Erneut versuchen",

    "sheet.minimize": "Minimieren",
    "sheet.restore": "Öffnen",
    "sheet.close": "Schließen",
    "sheet.pinTabs": "Tableiste anheften — alle Tabs bleiben über dem offenen Ticket",
    "sheet.unpinTabs": "Tableiste lösen",
    "sheet.dragHandle": "Größe ändern",
    "sheet.heading": "Case · {name}",
    "sheet.placeholderActions": "Aktions-Buttons (Status, Kommentar, Owner) kommen hier rein sobald sie verkabelt sind — vorerst nur Anzeige.",
    "sheet.loadingLive": "Lade Live-Casedaten…",
    "sheet.fallbackMock": "Zeige zwischengespeicherte Daten — Backend nicht erreichbar.",
    "sheet.liveBadge": "● LIVE",
    "sheet.liveTitle": "Zeigt Live-Daten aus Salesforce",
    "sheet.cachedBadge": "● CACHED",
    "sheet.fieldStatus": "Status",
    "sheet.fieldPriority": "Priorität",
    "sheet.fieldLocation": "Standort",
    "sheet.fieldSubject": "Subject",
    "sheet.fieldAssetName": "Asset",
    "sheet.fieldAssetLocation": "Asset-Pfad",
    "sheet.fieldAssetType": "Asset-Typ",
    "sheet.fieldCreated": "Erstellt",
    "sheet.fieldAssignee": "Assignee",
    "sheet.fieldDescription": "Beschreibung",
    "sheet.fieldCoolan": "Coolan Reporting State",

    "chatter.tabChatter": "Chatter",
    "chatter.tabCaseComments": "Case Comments",
    "chatter.tabEmail": "E-Mails",
    "chatter.placeholder": "Kommentar schreiben…",
    "chatter.replyPlaceholder": "Antwort…",
    "chatter.post": "Senden",
    "chatter.reply": "Antworten",
    "chatter.cancelReply": "Abbrechen",
    "chatter.empty": "Noch nichts hier.",
    "chatter.edit": "Bearbeiten",
    "chatter.save": "Speichern",
    "chatter.replies": "Antworten",

    "sheet.editStatus": "Status ändern",
    "sheet.vendorCaseNumber": "Vendor Case Number",
    "sheet.vendorCaseNumberHint": "Ein Vendor ist auf diesem Case eingeplant — Eskorte nötig.",
    "sheet.pickParentFirst": "Erst die übergeordnete Kategorie auswählen",
    "sheet.editSection": "Bearbeiten",
    "sheet.saveSection": "Änderungen prüfen",
    "sheet.cancelSection": "Abbrechen",
    "sheet.collapseSection": "{name} einklappen",
    "sheet.expandSection": "{name} ausklappen",

    "edit.confirmTitle": "Änderungen prüfen",
    "edit.confirmSubtitle": "{count} Feld(er) auf Case {caseNumber}",
    "edit.sectionCase": "Case",
    "edit.sectionAsset": "Asset",
    "edit.colField": "Feld",
    "edit.colOld": "Aktueller Wert",
    "edit.colNew": "Neuer Wert",
    "edit.cancel": "Abbrechen",
    "edit.edit": "Zurück zum Bearbeiten",
    "edit.confirmWrite": "Bestätigen und speichern",
    "edit.confirmDryRun": "Bestätigen (Trockenlauf)",
    "edit.dryRunHeader": "Schreibmodus ist AUS.",
    "edit.dryRunBody": "Bestätigen loggt nur die geplanten Änderungen. Aktiviere den Schreiben-Toggle im Header, um wirklich nach Salesforce zu schreiben.",
    "edit.toastSaved": "Gespeichert",
    "edit.toastDryRun": "Trockenlauf geloggt",
    "edit.toastPosted": "Kommentar gepostet",
    "common.close": "Schließen",
    "common.openInGus": "In GUS öffnen",
    "common.openInGusAndMark": "In GUS öffnen (markiert auch als gesehen)",
    "common.clickForFullText": "Klicken für vollen Text",
    "common.tooltipClose": "Tooltip schließen",
    "common.tooltipResize": "Größe ändern",

    "donut.active": "AKTIV",
    "donut.rtsTodayShort": "RTS heute",
    "donut.rtsTodayFull": "Return to Service heute",
    "donut.totalRuntime": "Gesamt-Laufzeit",
    "donut.hint": "Klick auf ein Segment im Kreisdiagramm öffnet die Ticket-Liste für diesen Status.",

    "legend.title": "Aktive RMA-Übersicht",
    "legend.rtsToday": "Return to Service",
    "legend.rtsTodayHint": "heute",
    "legend.rtsTodayTitle": "Anzahl der Frankfurt-Cases die heute auf Return to Service gewechselt sind",
    "legend.myOpen": "Von mir noch offen",
    "legend.myOpenTitle": "Cases die du auf Return to Service gesetzt hast und die noch nicht geschlossen sind. Klicken zum Ein-/Ausklappen.",
    "legend.closed": "Bereits geschlossen",
    "legend.closedHint": "(180d)",
    "legend.closedTitle": "Tickets die du auf Return to Service gesetzt hast und die seitdem geschlossen wurden (letzte 180 Tage)",
    "legend.tableTicket": "Ticket",
    "legend.tableLocation": "Ort",
    "legend.tableSubject": "Subject",
    "legend.tableSetAt": "Gesetzt",

    "details.heading": "Details: {status} ({count})",
    "details.colPriority": "Prio",
    "details.colTicketId": "Ticket-ID",
    "details.colLocation": "Standort",
    "details.colType": "Subject",
    "details.colCreated": "Erstellt",
    "details.colStatusChanged": "Status seit",
    "details.colAssignee": "Assignee",
    "details.colAssetName": "Asset",
    "details.colAssetLocation": "Asset-Pfad",
    "details.colAssetType": "Asset-Typ",
    "details.colDescription": "Beschreibung",
    "details.colCoolan": "Coolan",
    "details.colGus": "GUS",
    "details.tooltipTitle": "Subject · {name}",
    "details.coolanTooltipTitle": "Coolan · {name}",
    "details.coolanNoneAvailable": "Keine Coolan-Links",
    "details.componentTooltipFor": "Komponente am Case {ticketId}",
    "details.componentNoAttributes": "Coolan hat keine Detailinformationen zu dieser Komponente geliefert.",
    "details.coolanStateMissing": "Reporting State: Missing — Host meldet sich nicht in Coolan.",
    "details.coolanStateActive": "Reporting State: Active — Host läuft und meldet sich.",
    "details.coolanStateUnknown": "Reporting State: unbekannt — Coolan hat keinen Eintrag für dieses Asset.",
    "details.columnsManager": "Spalten",
    "details.columnsManagerTitle": "Spalten",
    "details.columnsManagerReset": "Zurücksetzen",
    "details.columnsManagerHint": "Per Griff verschieben. Häkchen entfernen zum Ausblenden.",
    "filter.label": "Filter",
    "filter.column": "Filter-Spalte",
    "filter.columnPlaceholder": "Spalte wählen…",
    "filter.value": "Filterwert",
    "filter.placeholder": "Filtertext eingeben…",
    "filter.clear": "Filter zurücksetzen",
    "filter.counter": "{shown} von {total} angezeigt",

    "activity.title": "Aktivitätslog",
    "activity.outsideHint": "außerhalb {start}–{end} Uhr markiert",
    "activity.outsideHours": "Außerhalb der Arbeitszeit ({start}–{end} Uhr)",
    "activity.newCase": "Neuer Fall",
    "activity.mentionsMe": "Erwähnt dich / @DCEng-FRA3",
    "activity.botsOn": "Bots an",
    "activity.botsOff": "Bots aus",
    "activity.toggleBotsTitle": "Service-Account-Events ein-/ausblenden (z.B. svc_grok-fra)",
    "activity.filterAll": "Alle",
    "activity.filterStatus": "Status",
    "activity.filterComment": "Kommentare",
    "activity.filterMe": "Ich",
    "activity.filterMeTitle": "Nur Ereignisse die {name} betreffen (Akteur oder Erwähnung)",
    "activity.statusFilter": "Statusfilter",
    "activity.statusClear": "Zurücksetzen",
    "activity.searchComments": "Kommentare suchen…",
    "activity.searchTickets": "Ticket #",
    "activity.searchTicketsTitle": "Ticket-Nummer eingeben, um nur die Historie dieses Cases zu sehen. Andere Filter werden ignoriert, solange das Feld aktiv ist.",
    "activity.colTime": "Zeit",
    "activity.colTicket": "Ticket",
    "activity.colLocation": "Ort",
    "activity.colEvent": "Ereignis",
    "activity.colActor": "Akteur",
    "activity.colGus": "GUS",
    "activity.markSeen": "Als gesehen markieren",
    "activity.markNew": "Als neu markieren",
    "activity.markSeenTitle": "Neu — als gesehen markieren",
    "activity.markNewTitle": "Gesehen — als neu markieren",
    "activity.eventStatus": "Status:",
    "activity.eventComment": "Kommentar:",
    "activity.empty": "Keine Aktivitäten",
    "activity.commentTooltipTitle": "Kommentar · {ticketId}",
  },
} as const;

export type TranslationKey = keyof (typeof dict)["en"];

function loadInitial(): Language {
  try {
    const v = localStorage.getItem(STORAGE_KEY);
    if (v === "en" || v === "de") return v;
  } catch {
    /* ignore */
  }
  return DEFAULT_LANGUAGE;
}

interface LanguageContextValue {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: TranslationKey, vars?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>(() => loadInitial());

  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, lang);
    } catch {
      /* ignore */
    }
    document.documentElement.lang = lang;
  }, [lang]);

  const t = useCallback(
    (key: TranslationKey, vars?: Record<string, string | number>): string => {
      const template: string = dict[lang][key] ?? dict.en[key] ?? key;
      if (!vars) return template;
      return Object.entries(vars).reduce<string>(
        (acc, [k, v]) => acc.replaceAll(`{${k}}`, String(v)),
        template,
      );
    },
    [lang],
  );

  const value = useMemo(() => ({ lang, setLang, t }), [lang, t]);
  return createElement(LanguageContext.Provider, { value }, children);
}

export function useLanguage(): LanguageContextValue {
  const ctx = useContext(LanguageContext);
  if (ctx) return ctx;
  // No provider (e.g. in unit tests): return a stable no-op-setter
  // value so components render with English defaults.
  const lang: Language = DEFAULT_LANGUAGE;
  const t = (key: TranslationKey, vars?: Record<string, string | number>): string => {
    const template: string = dict[lang][key] ?? key;
    if (!vars) return template;
    return Object.entries(vars).reduce<string>(
      (acc, [k, v]) => acc.replaceAll(`{${k}}`, String(v)),
      template,
    );
  };
  return { lang, setLang: () => {}, t };
}

export function localeFor(lang: Language): string {
  return lang === "de" ? "de-DE" : "en-GB";
}
